#!/bin/bash

#install docker on debian
sudo apt-get update
sudo apt-get install \
     apt-transport-https \
     ca-certificates \
     curl \
     gnupg2 \
     software-properties-common -y

curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -

sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/debian \
   $(lsb_release -cs) \
   stable"

sudo apt-get update
sudo apt-get install docker-ce -y

# Install the 64 bit Relay CLI utility (change curl link for 32 bit version)
# sudo apt-get update && sudo apt-get install -y curl
curl -L -o relay https://gitlab.com/norad/relay-cli/-/jobs/artifacts/master/raw/build/relay?job=build_linux_amd64
sudo chown root:root relay
sudo chmod 770 relay
sudo mv relay /usr/local/bin/relay
